name: Docker Image CI - Build and push image 

on:
  push:
    paths:
    - 'Dockerfile'
    
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag miniatureseal/dsci-310-group-10-gcc:latest .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker images
      run: docker push miniatureseal/dsci-310-group-10-gcc --all-tags
